name = "GFlops"
uuid = "2ea8233c-34d4-5acc-88b4-02f326385bcc"
license = "MIT"
authors = ["François Févotte <francois.fevotte@triscale-innov.com>"]
version = "0.1.5"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BenchmarkTools = "^0.4.2, 0.5, 0.6, 0.7"
Cassette = "^0.2.3, 0.3.2"
PrettyTables = "^0.12, 1.0"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
